name: Lint-test-build

on: [pull_request]

jobs: 
  Lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install
        run: npm install
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
